name: Build Plugin
on: [ push, pull_request ]
jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2.5.0
        with:
          distribution: 'zulu'
          java-version: 11
      - name: gradle build
        id: gradle
        uses: gradle/gradle-build-action@v2.1.0
        with:
          arguments: :build